### ISSUE TITLE
Check out presentation

### ISSUE THREAD

**Issue by JJ** [JJ/alife14-made#2]
@fergunet @raiben @amorag check out the presentation, comment when you do. Finally I will use my classical style, instead of rat drawings, but if you've got one that fits the text, please let me know. Check the result at http://jj.github.io/alife14-made/#/step-5

**Comment by fergunet** [comment]
@JJ Why some slides are being repeated? Is the presentation already finished? (IDK if it is a failure or it is still WIP)
